/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresetsRouteImport } from './routes/presets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharacterIdRouteImport } from './routes/character.$id'

const PresetsRoute = PresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterIdRoute = CharacterIdRouteImport.update({
  id: '/character/$id',
  path: '/character/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/presets': typeof PresetsRoute
  '/character/$id': typeof CharacterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/presets': typeof PresetsRoute
  '/character/$id': typeof CharacterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/presets': typeof PresetsRoute
  '/character/$id': typeof CharacterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/presets' | '/character/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/presets' | '/character/$id'
  id: '__root__' | '/' | '/presets' | '/character/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PresetsRoute: typeof PresetsRoute
  CharacterIdRoute: typeof CharacterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/presets': {
      id: '/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof PresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/$id': {
      id: '/character/$id'
      path: '/character/$id'
      fullPath: '/character/$id'
      preLoaderRoute: typeof CharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PresetsRoute: PresetsRoute,
  CharacterIdRoute: CharacterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
